# PR Forensics Extraction Script
# Extracts and categorizes ALL bot findings from a GitHub PR
# Usage: .\scripts\extract_pr_forensics.ps1 -PrNumber 6

param(
    [Parameter(Mandatory=$true)]
    [int]$PrNumber
)

$ErrorActionPreference = "Stop"

# Extract repository URL dynamically from git remote
$GitRemote = git remote get-url origin
$RepoUrl = $GitRemote -replace '\.git$', '' -replace 'git@github\.com:', 'https://github.com/'

Write-Host "=== PR FORENSICS EXTRACTION ===" -ForegroundColor Cyan
Write-Host "PR #$PrNumber" -ForegroundColor Yellow
Write-Host "Repository: $RepoUrl" -ForegroundColor Gray

# Step 1: Fetch raw data (JSON + full comments page)
Write-Host "`n[1/5] Fetching PR data from GitHub..." -ForegroundColor Green

# Fetch JSON data (structured)
$rawFile = "pr_${PrNumber}_raw.json"
gh pr view $PrNumber --json comments,reviews,statusCheckRollup | Out-File -FilePath $rawFile -Encoding utf8
$prData = Get-Content $rawFile | ConvertFrom-Json

# Fetch full comments page (includes inline review comments)
$commentsFile = "pr_${PrNumber}_comments.txt"
gh pr view $PrNumber --comments | Out-File -FilePath $commentsFile -Encoding utf8
$fullComments = Get-Content $commentsFile -Raw

# Step 2: Extract findings
Write-Host "[2/5] Parsing bot comments and reviews..." -ForegroundColor Green

$findings = @()
$hallucinations = @()

# Process comments
foreach ($comment in $prData.comments) {
    $author = $comment.author.login
    $body = $comment.body
    
    # Skip non-bot comments
    if ($author -notmatch "bot|ai|codacy|sourcery|coderabbit|amazon-q|gemini|greptile|cubic|codeant|codeslick|insight|gitar") {
        continue
    }
    
    # FILTER OUT BOT SUMMARIES (not actionable findings)
    $isSummary = $false
    
    # Pattern 1: Auto-generated summary comments
    if ($body -match "<!-- This is an auto-generated comment: summarize|<!-- auto-generated comment: summarize") {
        $isSummary = $true
    }
    # Pattern 2: Review guide headers
    elseif ($body -match "<!-- Generated by .+\[bot\]: start review_guide|## Reviewer's Guide") {
        $isSummary = $true
    }
    # Pattern 3: Positive summary headers (no actionable issues)
    elseif ($body -match "^## Code Review Summary" -and $body -match "successfully implements|without introducing blocking defects|no blocking issues") {
        $isSummary = $true
    }
    # Pattern 4: Walkthrough sections (informational only)
    elseif ($body -match "^## Walkthrough" -and $body -notmatch "Critical|Blocking|MUST|race condition|deadlock") {
        $isSummary = $true
    }
    
    # Skip summaries - they're not actionable findings
    if ($isSummary) {
        continue
    }
    
    # Classify comment (only if NOT a summary)
    $classification = "UNKNOWN"
    $priority = "P2"
    $category = "INFO"
    
    # INFRA-NOISE detection
    if ($body -match "Monthly limit|Analysis Blocked|upgrade to continue|No accessibility issues") {
        $classification = "INFRA-NOISE"
        $category = "INFRA"
    }
    # HALLUCINATION detection
    elseif ($body -match "missing files|file not found|cannot find" -and $body -notmatch "test coverage") {
        $classification = "HALLUCINATION"
        $hallucinations += @{
            bot = $author
            claim = ($body -split "`n" | Select-String "missing|not found" | Select-Object -First 1).ToString()
            timestamp = $comment.createdAt
        }
    }
    # VALID findings
    elseif ($body -match "Critical|Blocking|MUST|race condition|deadlock|struct copy|atomic") {
        $classification = "VALID"
        $priority = "P0"
        $category = "CRITICAL"
    }
    elseif ($body -match "High Risk|security|vulnerability|unsafe") {
        $classification = "VALID"
        $priority = "P1"
        $category = "SECURITY"
    }
    elseif ($body -match "performance|optimization|allocation|benchmark") {
        $classification = "VALID"
        $priority = "P2"
        $category = "PERFORMANCE"
    }
    
    if ($classification -ne "UNKNOWN") {
        $findings += [PSCustomObject]@{
            Source = "comment"
            Bot = $author
            Classification = $classification
            Priority = $priority
            Category = $category
            Timestamp = $comment.createdAt
            URL = $comment.url
            Body = $body.Substring(0, [Math]::Min(500, $body.Length))
        }
    }
}

# Process reviews
foreach ($review in $prData.reviews) {
    $author = $review.author.login
    $body = $review.body
    
    # Skip empty reviews
    if ([string]::IsNullOrWhiteSpace($body)) {
        continue
    }
    
    # FILTER OUT BOT SUMMARIES (not actionable findings)
    $isSummary = $false
    
    # Pattern 1: Auto-generated summary comments
    if ($body -match "<!-- This is an auto-generated comment: summarize|<!-- auto-generated comment: summarize") {
        $isSummary = $true
    }
    # Pattern 2: Review guide headers
    elseif ($body -match "<!-- Generated by .+\[bot\]: start review_guide|## Reviewer's Guide") {
        $isSummary = $true
    }
    # Pattern 3: Positive summary headers (no actionable issues)
    elseif ($body -match "^## Code Review Summary" -and $body -match "successfully implements|without introducing blocking defects|no blocking issues") {
        $isSummary = $true
    }
    # Pattern 4: Walkthrough sections (informational only)
    elseif ($body -match "^## Walkthrough" -and $body -notmatch "Critical|Blocking|MUST|race condition|deadlock") {
        $isSummary = $true
    }
    # Pattern 5: "Up to quality standards" (Codacy positive summary)
    elseif ($body -match "Pull Request Overview" -and $body -match "up to quality standards") {
        $isSummary = $true
    }
    
    # Skip summaries - they're not actionable findings
    if ($isSummary) {
        continue
    }
    
    # Classify review (only if NOT a summary)
    $classification = "VALID"
    $priority = "P1"
    $category = "REVIEW"
    
    if ($body -match "Critical|Blocking|MUST|P0") {
        $priority = "P0"
        $category = "CRITICAL"
    }
    elseif ($body -match "struct copy|race condition|atomic|CompareExchange|local variable") {
        $priority = "P0"
        $category = "CONCURRENCY"
    }
    
    $findings += [PSCustomObject]@{
        Source = "review"
        Bot = $author
        Classification = $classification
        Priority = $priority
        Category = $category
        Timestamp = $review.submittedAt
        URL = "$RepoUrl/pull/$PrNumber"
        Body = $body.Substring(0, [Math]::Min(500, $body.Length))
    }
}

# Step 2.5: Parse inline review comments from full comments page
Write-Host "[2.5/5] Parsing inline review comments..." -ForegroundColor Green

# Extract inline comments (format: "bot-name commented on line X in file.cs")
$inlinePattern = '(?m)^(\S+)\s+commented.*?on line (\d+).*?in\s+(\S+\.cs).*?\n\n(.*?)(?=\n\n\S+\s+commented|\z)'
$inlineMatches = [regex]::Matches($fullComments, $inlinePattern)

foreach ($match in $inlineMatches) {
    $author = $match.Groups[1].Value
    $lineNum = $match.Groups[2].Value
    $fileName = $match.Groups[3].Value
    $commentBody = $match.Groups[4].Value.Trim()
    
    # Skip non-bot comments
    if ($author -notmatch "bot|ai|codacy|sourcery|coderabbit|amazon-q|gemini|greptile|cubic|codeant|codeslick|insight|gitar") {
        continue
    }
    
    # Skip if already captured in JSON data (avoid duplicates)
    $isDuplicate = $findings | Where-Object { $_.Body -like "*$($commentBody.Substring(0, [Math]::Min(50, $commentBody.Length)))*" }
    if ($isDuplicate) {
        continue
    }
    
    # Filter out summaries
    $isSummary = $false
    if ($commentBody -match "<!-- This is an auto-generated comment: summarize|<!-- auto-generated comment: summarize") {
        $isSummary = $true
    }
    elseif ($commentBody -match "<!-- Generated by .+\[bot\]: start review_guide|## Reviewer's Guide") {
        $isSummary = $true
    }
    elseif ($commentBody -match "^## Code Review Summary" -and $commentBody -match "successfully implements|without introducing blocking defects") {
        $isSummary = $true
    }
    
    if ($isSummary) {
        continue
    }
    
    # Classify inline comment
    $classification = "VALID"
    $priority = "P1"
    $category = "INLINE"
    
    if ($commentBody -match "Critical|Blocking|MUST|P0|race condition|deadlock") {
        $priority = "P0"
        $category = "CRITICAL"
    }
    elseif ($commentBody -match "allocation|heap|string\.Format|StringBuilder") {
        $priority = "P0"
        $category = "PERFORMANCE"
    }
    
    $findings += [PSCustomObject]@{
        Source = "inline"
        Bot = $author
        Classification = $classification
        Priority = $priority
        Category = $category
        Timestamp = (Get-Date).ToString("o")
        URL = "$RepoUrl/pull/$PrNumber#discussion_r"
        Body = "${fileName}:${lineNum} - $($commentBody.Substring(0, [Math]::Min(400, $commentBody.Length)))"
    }
}

# Step 3: Generate forensics report
Write-Host "[3/5] Generating forensics report..." -ForegroundColor Green

$reportPath = "docs/brain/pr_${PrNumber}_forensics.md"
$reportContent = @"
# PR #$PrNumber Forensics Report
Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Summary

| Metric | Count |
|--------|-------|
| Total Findings | $($findings.Count) |
| VALID Issues | $(($findings | Where-Object Classification -eq "VALID").Count) |
| HALLUCINATIONS | $(($findings | Where-Object Classification -eq "HALLUCINATION").Count) |
| INFRA-NOISE | $(($findings | Where-Object Classification -eq "INFRA-NOISE").Count) |
| P0 (Critical) | $(($findings | Where-Object Priority -eq "P0").Count) |
| P1 (High) | $(($findings | Where-Object Priority -eq "P1").Count) |
| P2 (Medium) | $(($findings | Where-Object Priority -eq "P2").Count) |

## VALID Issues (Priority Order)

"@

# Group by priority
$validFindings = $findings | Where-Object Classification -eq "VALID" | Sort-Object @{Expression={
    switch ($_.Priority) {
        "P0" { 0 }
        "P1" { 1 }
        "P2" { 2 }
        default { 3 }
    }
}}

foreach ($finding in $validFindings) {
    $reportContent += @"

### [$($finding.Priority)] $($finding.Category) - $($finding.Bot)
**Source:** $($finding.Source)  
**Timestamp:** $($finding.Timestamp)  
**URL:** $($finding.URL)

**Excerpt:**
``````
$($finding.Body)
``````

"@
}

# Add hallucinations section
if ($hallucinations.Count -gt 0) {
    $reportContent += @"

## Hallucinations Log

"@
    foreach ($h in $hallucinations) {
        $reportContent += "- **$($h.bot)** @ $($h.timestamp): $($h.claim)`n"
    }
}

# Add INFRA-NOISE section
$infraNoise = $findings | Where-Object Classification -eq "INFRA-NOISE"
if ($infraNoise.Count -gt 0) {
    $reportContent += @"

## INFRA-NOISE (Ignored)

"@
    foreach ($noise in $infraNoise) {
        $reportContent += "- **$($noise.Bot)**: $($noise.Category)`n"
    }
}

$reportContent | Out-File -FilePath $reportPath -Encoding utf8

# Step 4: Generate fix queue
Write-Host "[4/5] Generating fix queue..." -ForegroundColor Green

$fixQueuePath = "docs/brain/pr_${PrNumber}_fix_queue.md"
$fixQueue = @"
# PR #$PrNumber Fix Queue
Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

## Instructions for v12-engineer

Process these issues in priority order. Mark each as FIXED after applying the fix.

"@

$fixNumber = 1
foreach ($finding in $validFindings) {
    $status = "[ ]"
    $fixQueue += @"

### Fix #$fixNumber - [$($finding.Priority)] $($finding.Category)
$status **Bot:** $($finding.Bot)  
$status **File:** (extract from body)  
$status **Issue:** $($finding.Body.Substring(0, [Math]::Min(200, $finding.Body.Length)))...

**Action Required:**
1. Read the full finding at: $($finding.URL)
2. Apply the fix
3. Verify locally
4. Mark as [x] FIXED

---

"@
    $fixNumber++
}

$fixQueue | Out-File -FilePath $fixQueuePath -Encoding utf8

# Step 5: Update hallucination log
Write-Host "[5/5] Updating persistent hallucination log..." -ForegroundColor Green

$hallucinationLogPath = "docs/brain/bot_hallucinations.md"
if (-not (Test-Path $hallucinationLogPath)) {
    "# Bot Hallucination Log`n`nTracks false positives for pattern learning.`n" | Out-File -FilePath $hallucinationLogPath -Encoding utf8
}

if ($hallucinations.Count -gt 0) {
    $hallucinationEntry = "`n## PR #$PrNumber - $(Get-Date -Format 'yyyy-MM-dd')`n"
    foreach ($h in $hallucinations) {
        $hallucinationEntry += "- **$($h.bot)**: $($h.claim)`n"
    }
    Add-Content -Path $hallucinationLogPath -Value $hallucinationEntry
}

# Summary
Write-Host "`n=== EXTRACTION COMPLETE ===" -ForegroundColor Cyan
Write-Host "Forensics Report: $reportPath" -ForegroundColor Yellow
Write-Host "Fix Queue: $fixQueuePath" -ForegroundColor Yellow
Write-Host "Hallucination Log: $hallucinationLogPath" -ForegroundColor Yellow
Write-Host "`nVALID Issues: $(($validFindings).Count)" -ForegroundColor Green
Write-Host "  P0 (Critical): $(($validFindings | Where-Object Priority -eq 'P0').Count)" -ForegroundColor Red
Write-Host "  P1 (High): $(($validFindings | Where-Object Priority -eq 'P1').Count)" -ForegroundColor Yellow
Write-Host "  P2 (Medium): $(($validFindings | Where-Object Priority -eq 'P2').Count)" -ForegroundColor Cyan
Write-Host "`nHallucinations: $($hallucinations.Count)" -ForegroundColor Magenta
Write-Host "INFRA-NOISE: $(($infraNoise).Count)" -ForegroundColor DarkGray

exit 0

# Made with Bob
