# Post-PR-Loop Hook
# Auto-generates PR summary after achieving 100/100 PHS
# Purpose: Document PR completion and provide merge-ready summary
# Exit Behavior: Continue (non-blocking)

param(
    [Parameter(Mandatory=$true)]
    [int]$PrNumber
)

$ErrorActionPreference = "Stop"

Write-Host "[POST-PR-LOOP] Generating PR summary for #$PrNumber..." -ForegroundColor Yellow

# 1. Extract commit messages
Write-Host "  [1/4] Extracting commits..." -ForegroundColor Cyan
try {
    $commits = git log origin/main..HEAD --oneline 2>&1
    if ($LASTEXITCODE -ne 0) {
        $commits = "Unable to extract commits (not on a branch?)"
    }
} catch {
    $commits = "Error extracting commits: $_"
}
Write-Host "  [1/4] Commits: EXTRACTED" -ForegroundColor Green

# 2. Extract fix queue completion status
Write-Host "  [2/4] Analyzing fix queue..." -ForegroundColor Cyan
$fixQueueFile = "docs/brain/pr_${PrNumber}_fix_queue.md"
$fixedCount = 0
$totalCount = 0
$fixQueueStatus = "Not found"

if (Test-Path $fixQueueFile) {
    try {
        $fixQueue = Get-Content $fixQueueFile -Raw
        $fixedCount = ([regex]::Matches($fixQueue, "\[x\]")).Count
        $totalCount = ([regex]::Matches($fixQueue, "\[[ x]\]")).Count
        $fixQueueStatus = "Analyzed"
    } catch {
        $fixQueueStatus = "Error reading file"
    }
}
Write-Host "  [2/4] Fix Queue: $fixQueueStatus" -ForegroundColor Green

# 3. Extract CI logs status
Write-Host "  [3/4] Checking CI logs..." -ForegroundColor Cyan
$ciLogsFile = "docs/brain/pr_${PrNumber}_ci_logs.md"
$ciStatus = if (Test-Path $ciLogsFile) { "Available" } else { "Not found" }
Write-Host "  [3/4] CI Logs: $ciStatus" -ForegroundColor Green

# 4. Extract forensics status
Write-Host "  [4/4] Checking forensics..." -ForegroundColor Cyan
$forensicsFile = "pr_${PrNumber}_full.json"
$forensicsStatus = if (Test-Path $forensicsFile) { "Available" } else { "Not found" }
Write-Host "  [4/4] Forensics: $forensicsStatus" -ForegroundColor Green

# 5. Generate summary
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$summary = @"
# PR #$PrNumber Summary

**Status**: Ready for Merge (PHS 100/100)  
**Generated**: $timestamp  
**Generated by**: post-pr-loop hook

---

## Commits

``````
$commits
``````

---

## Issues Fixed

- **Total Issues**: $totalCount
- **Completed**: $fixedCount
- **Remaining**: $($totalCount - $fixedCount)
- **Completion Rate**: $(if ($totalCount -gt 0) { [math]::Round(($fixedCount / $totalCount) * 100, 2) } else { 0 })%

---

## Validation Checklist

- ✅ All tests passed
- ✅ All bot checks passed
- ✅ F5 verification complete
- ✅ PHS score: 100/100
- ✅ No merge conflicts
- ✅ Branch rebased on main

---

## Artifacts

- Fix Queue: $fixQueueStatus ($fixQueueFile)
- CI Logs: $ciStatus ($ciLogsFile)
- Forensics: $forensicsStatus ($forensicsFile)

---

## Next Steps

1. Review this summary
2. Verify all changes are intentional
3. Merge PR via GitHub UI
4. Delete feature branch after merge
5. Pull latest main locally

---

**Note**: This summary was auto-generated by the post-pr-loop hook.  
For manual edits, modify this file directly.
"@

# 6. Write summary
$summaryFile = "docs/brain/pr_${PrNumber}_summary.md"
try {
    # Ensure directory exists
    $summaryDir = Split-Path $summaryFile -Parent
    if (-not (Test-Path $summaryDir)) {
        New-Item -ItemType Directory -Path $summaryDir -Force | Out-Null
    }
    
    $summary | Out-File -FilePath $summaryFile -Encoding UTF8 -Force
    Write-Host "`n[POST-PR-LOOP] Summary written to: $summaryFile" -ForegroundColor Green
    
    # Display summary location
    Write-Host "`nSummary Details:" -ForegroundColor Cyan
    Write-Host "  File: $summaryFile" -ForegroundColor Gray
    Write-Host "  Commits: $($commits -split "`n" | Measure-Object).Count" -ForegroundColor Gray
    Write-Host "  Issues Fixed: $fixedCount/$totalCount" -ForegroundColor Gray
    
} catch {
    Write-Host "[POST-PR-LOOP] WARN: Failed to write summary" -ForegroundColor Yellow
    Write-Host "  Error: $_" -ForegroundColor Red
    exit 0  # Non-blocking
}

Write-Host "[POST-PR-LOOP] COMPLETE: PR #$PrNumber ready for merge" -ForegroundColor Green
exit 0

# Made with Bob
